# Generated by Django 2.0.4 on 2018-04-23 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_type', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('team_lead', models.CharField(max_length=200)),
                ('date_started', models.DateField(default=datetime.date.today)),
                ('date_due', models.DateField()),
                ('tools_needed', models.TextField()),
                ('date_completed', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
