# Generated by Django 2.0.4 on 2018-04-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
